Init Docs v2 project
polywrap/projects pull request #3
Opened 2023-01-11 20:08 UTC by pileks

2023-01-11 23:37 UTC, dOrgJelli requested changes

2023-01-11 23:37 UTC, dOrgJelli commented on in-progress/documentation-v2.md
> +[HackMD detailing Docs V2 outline](https://hackmd.io/qiDX0EX8SnqJE-Q9mGJOcQ)
Hey Jure, could we extract the important bits from the HackMD doc and put them in this doc?

2023-01-11 23:37 UTC, dOrgJelli commented on in-progress/documentation-v2.md
> +  - All issues that are not directly linked to the outline should be removed from the roadmap for the duration of the project
I don't know if we need to modify the roadmap. IMO the roadmap is a higher-order planning tool. This project is merely tackling a subset of tasks within the docs roadmap.

If we extract the "goals" from the HackMD doc above, and put them here, we can more easily detail what issues in the roadmap represent these goals.

2023-01-11 23:37 UTC, dOrgJelli commented on in-progress/documentation-v2.md
> +- Update Doc website styles to align with the Polywrap website redesign
Just a comment: this could be done pretty simply with a color pallet update + changing the logo in the header. I think that's all the branding we have in the docs.

2023-01-11 23:37 UTC, dOrgJelli commented on in-progress/documentation-v2.md
> +## Non-Goals
Is another non-goal maybe "supporting multiple versions of the referenced packages within the documentation"?

2023-01-11 23:37 UTC, dOrgJelli commented on in-progress/documentation-v2.md
> +## Impact
I really liked what you put here, really great impact & motivation!

2023-01-12 18:11 UTC, kev-ngo submitted a review, later dismissed

2023-01-14 12:19 UTC, krisbitney commented on in-progress/documentation-v2.md
> +## Non-Goals
I agree with this as a non-goal. Maybe after this project we can follow up with a QA project where we make revisions and implement multi-version support. We will want to consider how to handle packages being on different versions.

Having versioned release branches in the toolchain repo will make multi-version support for reference docs easier to implement since it's clear which branch is associated with which version and we can rely on them not being deleted. Maybe we should follow that practice for all of our packages?

2023-01-14 12:19 UTC, krisbitney approved these changes

2023-01-16 15:17 UTC, pileks commented on in-progress/documentation-v2.md
> +[HackMD detailing Docs V2 outline](https://hackmd.io/qiDX0EX8SnqJE-Q9mGJOcQ)
Agreed!

2023-01-16 15:17 UTC, pileks commented on in-progress/documentation-v2.md
> +  - All issues that are not directly linked to the outline should be removed from the roadmap for the duration of the project
Agreed, will remove this and update with concrete tasks here.

2023-01-17 02:27 UTC, dOrgJelli approved these changes

2023-01-17 02:28 UTC, merged